//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SobitsInterfaces
{
    [Serializable]
    public class VlaRecordStatusMsg : Message
    {
        public const string k_RosMessageName = "sobits_interfaces/VlaRecordStatus";
        public override string RosMessageName => k_RosMessageName;

        //  Recorder status of sobits_vla_rosbag_collection, published on ~/record_status
        //  (resolves to /<robot>/vla_rosbag_collection/record_status): a 1 Hz heartbeat
        //  (event = EVENT_NONE) plus one message immediately on every transition.
        //  Same numbers as VlaCommand.Response STATE_* so clients can copy the value.
        public const byte STATE_STOPPED = 0;
        public const byte STATE_RECORDING = 1;
        public const byte STATE_PAUSED = 2;
        public const byte STATE_ERROR = 4;
        public const byte EVENT_NONE = 0; //  heartbeat, nothing new since the last event
        public const byte EVENT_STARTED = 1;
        public const byte EVENT_PAUSED = 2;
        public const byte EVENT_RESUMED = 3;
        public const byte EVENT_SAVED = 4;
        public const byte EVENT_DISCARDED = 5; //  detail: "too_short" | "integrity_failed"
        public const byte EVENT_DELETED = 6;
        public const byte EVENT_ERROR = 7; //  detail: error text
        public const byte EVENT_TASK_SET = 8; //  detail: task name
        public const byte EVENT_REJECTED = 9; //  a command was refused; detail: reason; state unchanged
        public BuiltinInterfaces.TimeMsg stamp;
        public byte state;
        public byte @event;
        public uint event_seq;
        //  increments once per event, not per heartbeat
        public bool task_set;
        //  false until vla_task_update succeeded once
        public string task_name;
        //  "" while task_set is false
        public string episode_name;
        //  current/last bag name (episode_<ts>), "" before the first RECORD
        public float elapsed_sec;
        //  recorded time of the episode, pauses excluded; frozen while
        //  paused; keeps the final value after save/discard/delete
        public string detail;
        //  event payload, see EVENT_* comments
        public string message;
        //  human-readable: "idle" | "recording HH:MM:SS" | "paused HH:MM:SS" |
        //  "error" | "saved" | "discarded" | "deleted" | "task_set: <name>"

        public VlaRecordStatusMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.state = 0;
            this.@event = 0;
            this.event_seq = 0;
            this.task_set = false;
            this.task_name = "";
            this.episode_name = "";
            this.elapsed_sec = 0.0f;
            this.detail = "";
            this.message = "";
        }

        public VlaRecordStatusMsg(BuiltinInterfaces.TimeMsg stamp, byte state, byte @event, uint event_seq, bool task_set, string task_name, string episode_name, float elapsed_sec, string detail, string message)
        {
            this.stamp = stamp;
            this.state = state;
            this.@event = @event;
            this.event_seq = event_seq;
            this.task_set = task_set;
            this.task_name = task_name;
            this.episode_name = episode_name;
            this.elapsed_sec = elapsed_sec;
            this.detail = detail;
            this.message = message;
        }

        public static VlaRecordStatusMsg Deserialize(MessageDeserializer deserializer) => new VlaRecordStatusMsg(deserializer);

        private VlaRecordStatusMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.state);
            deserializer.Read(out this.@event);
            deserializer.Read(out this.event_seq);
            deserializer.Read(out this.task_set);
            deserializer.Read(out this.task_name);
            deserializer.Read(out this.episode_name);
            deserializer.Read(out this.elapsed_sec);
            deserializer.Read(out this.detail);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.state);
            serializer.Write(this.@event);
            serializer.Write(this.event_seq);
            serializer.Write(this.task_set);
            serializer.Write(this.task_name);
            serializer.Write(this.episode_name);
            serializer.Write(this.elapsed_sec);
            serializer.Write(this.detail);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "VlaRecordStatusMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nstate: " + state.ToString() +
            "\n@event: " + @event.ToString() +
            "\nevent_seq: " + event_seq.ToString() +
            "\ntask_set: " + task_set.ToString() +
            "\ntask_name: " + task_name.ToString() +
            "\nepisode_name: " + episode_name.ToString() +
            "\nelapsed_sec: " + elapsed_sec.ToString() +
            "\ndetail: " + detail.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
