//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SobitsInterfaces
{
    [Serializable]
    public class VlaStatusMsg : Message
    {
        public const string k_RosMessageName = "sobits_interfaces/VlaStatus";
        public override string RosMessageName => k_RosMessageName;

        //  Status of a sobits_vla_tools stage node, published on ~/status:
        //    /<robot>/vla_rosbag_collection/status  (recorder, STAGE_COLLECTION)
        //    /<robot>/sobits_vla_deploy/status      (deploy,   STAGE_DEPLOY)
        //  A 1 Hz heartbeat (event = EVENT_NONE) plus one message immediately on every transition.
        public const byte STAGE_COLLECTION = 0;
        public const byte STAGE_DEPLOY = 1;
        //  Same numbers as VlaCommand.Response STATE_*; RESETTING is status-only.
        public const byte STATE_STOPPED = 0;
        public const byte STATE_RECORDING = 1;
        public const byte STATE_PAUSED = 2;
        public const byte STATE_PLAYING = 3;
        public const byte STATE_ERROR = 4;
        public const byte STATE_RESETTING = 5;
        public const byte EVENT_NONE = 0; //  heartbeat, nothing new since the last event
        public const byte EVENT_STARTED = 1; //  recording / playing began
        public const byte EVENT_PAUSED = 2;
        public const byte EVENT_RESUMED = 3;
        public const byte EVENT_SAVED = 4;
        public const byte EVENT_DISCARDED = 5; //  detail: "too_short" | "integrity_failed"
        public const byte EVENT_DELETED = 6;
        public const byte EVENT_ERROR = 7; //  detail: error text
        public const byte EVENT_TASK_SET = 8; //  detail: task name
        public const byte EVENT_REJECTED = 9; //  a command was refused; detail: reason; state unchanged
        public const byte EVENT_STOPPED = 10; //  deploy: PLAY ended, world reset starting; outcome set
        public const byte EVENT_EPISODE_DONE = 11; //  deploy: reset after an episode finished (mirrors ~/episode_done); outcome set
        public const byte EVENT_ENGAGED = 12; //  deploy: deadman pressed, actions flowing
        public const byte EVENT_RELEASED = 13; //  deploy: deadman released, robot held
        public const byte EVENT_RESET_DONE = 14; //  deploy: an idle STOP/RESET world reset finished (no episode)
        public BuiltinInterfaces.TimeMsg stamp;
        public byte stage;
        public byte state;
        public byte @event;
        public uint event_seq;
        //  increments once per event, not per heartbeat
        public bool task_set;
        //  false until the task was set once
        public string task_name;
        //  "" while task_set is false
        public string episode_name;
        //  recorder: bag name (episode_<ts>); deploy: episode_<n> of this process
        public float elapsed_sec;
        //  recorder: recorded time, pauses excluded, frozen while paused.
        //  deploy: the node's episode clock (from PLAY, or from the first
        //  deadman engagement), frozen at stop. Keeps the final value after.
        public string detail;
        //  event payload, see EVENT_* comments
        public string message;
        //  human-readable. recorder: "idle" | "recording HH:MM:SS" | "paused HH:MM:SS" |
        //  "error" | "saved" | "discarded" | "deleted" | "task_set: <name>".
        //  deploy: "idle" | "playing HH:MM:SS" | "playing HH:MM:SS (released)" |
        //  "resetting" | "done: <outcome>" | "error"
        //  Deploy stage only (zero / empty from the recorder)
        public string policy;
        //  model.repo_id ("fake" in the dry run)
        public bool deadman_enabled;
        public bool deadman_engaged;
        public uint steps;
        //  control steps executed in this episode
        public float inference_hz;
        //  action-chunk inferences per second (rolling window); 0 when idle
        public string outcome;
        //  manual_stop | success_lift | success_place | fallen | timeout | dropped | reset;
        //  set with EVENT_STOPPED / EVENT_EPISODE_DONE, "" while playing

        public VlaStatusMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.stage = 0;
            this.state = 0;
            this.@event = 0;
            this.event_seq = 0;
            this.task_set = false;
            this.task_name = "";
            this.episode_name = "";
            this.elapsed_sec = 0.0f;
            this.detail = "";
            this.message = "";
            this.policy = "";
            this.deadman_enabled = false;
            this.deadman_engaged = false;
            this.steps = 0;
            this.inference_hz = 0.0f;
            this.outcome = "";
        }

        public VlaStatusMsg(BuiltinInterfaces.TimeMsg stamp, byte stage, byte state, byte @event, uint event_seq, bool task_set, string task_name, string episode_name, float elapsed_sec, string detail, string message, string policy, bool deadman_enabled, bool deadman_engaged, uint steps, float inference_hz, string outcome)
        {
            this.stamp = stamp;
            this.stage = stage;
            this.state = state;
            this.@event = @event;
            this.event_seq = event_seq;
            this.task_set = task_set;
            this.task_name = task_name;
            this.episode_name = episode_name;
            this.elapsed_sec = elapsed_sec;
            this.detail = detail;
            this.message = message;
            this.policy = policy;
            this.deadman_enabled = deadman_enabled;
            this.deadman_engaged = deadman_engaged;
            this.steps = steps;
            this.inference_hz = inference_hz;
            this.outcome = outcome;
        }

        public static VlaStatusMsg Deserialize(MessageDeserializer deserializer) => new VlaStatusMsg(deserializer);

        private VlaStatusMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.stage);
            deserializer.Read(out this.state);
            deserializer.Read(out this.@event);
            deserializer.Read(out this.event_seq);
            deserializer.Read(out this.task_set);
            deserializer.Read(out this.task_name);
            deserializer.Read(out this.episode_name);
            deserializer.Read(out this.elapsed_sec);
            deserializer.Read(out this.detail);
            deserializer.Read(out this.message);
            deserializer.Read(out this.policy);
            deserializer.Read(out this.deadman_enabled);
            deserializer.Read(out this.deadman_engaged);
            deserializer.Read(out this.steps);
            deserializer.Read(out this.inference_hz);
            deserializer.Read(out this.outcome);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.stage);
            serializer.Write(this.state);
            serializer.Write(this.@event);
            serializer.Write(this.event_seq);
            serializer.Write(this.task_set);
            serializer.Write(this.task_name);
            serializer.Write(this.episode_name);
            serializer.Write(this.elapsed_sec);
            serializer.Write(this.detail);
            serializer.Write(this.message);
            serializer.Write(this.policy);
            serializer.Write(this.deadman_enabled);
            serializer.Write(this.deadman_engaged);
            serializer.Write(this.steps);
            serializer.Write(this.inference_hz);
            serializer.Write(this.outcome);
        }

        public override string ToString()
        {
            return "VlaStatusMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nstage: " + stage.ToString() +
            "\nstate: " + state.ToString() +
            "\n@event: " + @event.ToString() +
            "\nevent_seq: " + event_seq.ToString() +
            "\ntask_set: " + task_set.ToString() +
            "\ntask_name: " + task_name.ToString() +
            "\nepisode_name: " + episode_name.ToString() +
            "\nelapsed_sec: " + elapsed_sec.ToString() +
            "\ndetail: " + detail.ToString() +
            "\nmessage: " + message.ToString() +
            "\npolicy: " + policy.ToString() +
            "\ndeadman_enabled: " + deadman_enabled.ToString() +
            "\ndeadman_engaged: " + deadman_engaged.ToString() +
            "\nsteps: " + steps.ToString() +
            "\ninference_hz: " + inference_hz.ToString() +
            "\noutcome: " + outcome.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
